---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
data:
  DB_HOST: "host.minikube.internal"
  DB_PORT: "5432"
  DB_NAME: "my_todo_db"
  DB_USER: "my_app_user"
  PORT: "5000"
  FRONTEND_URL: "http://frontend-service"
 
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: todo-app
type: Opaque
# echo -n '1234' | base64  =>  MTIzNA==
data:
  DB_PASSWORD: MTIzNA==
 