---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secret
  namespace: raju
spec:
  encryptedData:
    DB_PASSWORD: AgBU/cBj9GTuWtxpfAlL+v7C8EqM5S5l8H4XiA5z+G3pqn0SEAqP/g9KIg5QHW8Y1h9NflXjrynWXiY2RFVfRSKJFdp22J5GWbXKPCDUVLj++Ds1/N8Oz/HmQY0eduSKPysVXwcehLt5ItR5zqY/Wbcg5N8Y7jTNVwz4Jc55pMagSDFAQyZX3ZqkJ4HtoH8MP4u7gmTOBBPFB85ikj6QJMwt8I2Nqx/jSFXGBlGX6bH6VNJdG9pMUpB6mvz1cA7lbNSpzz2qI1ifL4nXXiGEO18OS+8Vno8pHQzS5NtI6GkzgCDZKiXR0cxjxwPWkBluXNsSNA0cfJH1YHp4OY4EWxBY+9uQ87EDw+sZvWW/mivNS3hbRZhr3uDGto6EP7BfYGhvybKRgBgXrJJTbvx1UuhKG9uM6yCQtB/r4RZkflZRP4SONmaWlRPkALfX9+v2uiAiX2yM7iNWQUENbzutk6EEfrrrjcD/zCLQHPgtuEQ+9PLQM8KJvc5FcwgMi4GtO55Qz9zTSf13SIu4NTXW9G5Vh9tVe3oln6svIVdeiiBpwcN3d1xCc5NwCTWYRVnqOE5O8EvK7Ick5FHYBiqE281mKcOn/P5+9SXlb6QnwQUrZk1pjvY36j3EOOz5ym41+7Ad9Fb8XOUe6HRRIoeSnIEgZZJv6yC1mVI7UzqPwz32C0xU9mApnhjD92522kRCZzX5NIaU
  template:
    metadata:
      creationTimestamp: null
      name: todo-secret
      namespace: raju
    type: Opaque
