FROM debezium/connect:2.4

USER root

RUN curl -fSL -o /tmp/es-connector.zip \
  "https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-elasticsearch/versions/14.0.12/confluentinc-kafka-connect-elasticsearch-14.0.12.zip" \
  && mkdir -p /kafka/connect/elasticsearch \
  && unzip /tmp/es-connector.zip -d /kafka/connect/elasticsearch \
  && rm /tmp/es-connector.zip

USER 1001
