apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: cdc-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      hostAliases:
      - hostName: "host.docker.internal"
        ip: "192.168.49.1"
      containers:
      - name: kafka-connect
        image: debezium/connect:2.4
        ports:
        - containerPort: 8083
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: GROUP_ID
          value: "debezium-group"
        - name: CONFIG_STORAGE_TOPIC
          value: "debezium_config"
        - name: OFFSET_STORAGE_TOPIC
          value: "debezium_offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "debezium_status"
        - name: CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        readinessProbe:
          httpGet:
            path: /connectors
            port: 8083
          initialDelaySeconds: 15
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: cdc-stack
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
  selector:
    app: kafka-connect